apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: integration-kafka-processor-example
  links:
    - url: https://api-strategy.docs.gjensidige.io/principles-and-guidelines/technology-specific-guidelines/guidelines_datastreams
      title: Gjensidige event streams guidelines
      icon: dashboard
  description: This processor is made to test Kafka concepts.
  tags:
    - kafka
    - grpc
    - example
spec:
  type: grpc
  lifecycle: production
  owner: team-integration
  definition:
    $text: fan.proto

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integration-kafka-processor-example
  description: This processor is made to test Kafka concepts.
spec:
  type: kafka-processor
  lifecycle: production
  owner: team-integration
  system: example-system
#  dependsOn:
#    - resource:default/artists-db
  providesApis:
    - integration-kafka-processor-example
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Confluent Cloud
  description: Kafka cluster
spec:
  type: kafka-cluster
  lifecycle: production
  owner: team-integration
  system: kafka
  #  dependsOn:
  #    - resource:default/artists-db
#  providesApis:
#    - integration-kafka-processor-example